/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppTableauDeBordRouteImport } from './routes/_app/tableau-de-bord'
import { Route as AppProspectionIndexRouteImport } from './routes/_app/prospection.index'
import { Route as AppProspectionLeadIdRouteImport } from './routes/_app/prospection.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTableauDeBordRoute = AppTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectionIndexRoute = AppProspectionIndexRouteImport.update({
  id: '/prospection/',
  path: '/prospection/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectionLeadIdRoute = AppProspectionLeadIdRouteImport.update({
  id: '/prospection/$leadId',
  path: '/prospection/$leadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tableau-de-bord': typeof AppTableauDeBordRoute
  '/prospection/$leadId': typeof AppProspectionLeadIdRoute
  '/prospection/': typeof AppProspectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tableau-de-bord': typeof AppTableauDeBordRoute
  '/prospection/$leadId': typeof AppProspectionLeadIdRoute
  '/prospection': typeof AppProspectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/tableau-de-bord': typeof AppTableauDeBordRoute
  '/_app/prospection/$leadId': typeof AppProspectionLeadIdRoute
  '/_app/prospection/': typeof AppProspectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tableau-de-bord' | '/prospection/$leadId' | '/prospection/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tableau-de-bord' | '/prospection/$leadId' | '/prospection'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/tableau-de-bord'
    | '/_app/prospection/$leadId'
    | '/_app/prospection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tableau-de-bord': {
      id: '/_app/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AppTableauDeBordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospection/': {
      id: '/_app/prospection/'
      path: '/prospection'
      fullPath: '/prospection/'
      preLoaderRoute: typeof AppProspectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospection/$leadId': {
      id: '/_app/prospection/$leadId'
      path: '/prospection/$leadId'
      fullPath: '/prospection/$leadId'
      preLoaderRoute: typeof AppProspectionLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTableauDeBordRoute: typeof AppTableauDeBordRoute
  AppProspectionLeadIdRoute: typeof AppProspectionLeadIdRoute
  AppProspectionIndexRoute: typeof AppProspectionIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTableauDeBordRoute: AppTableauDeBordRoute,
  AppProspectionLeadIdRoute: AppProspectionLeadIdRoute,
  AppProspectionIndexRoute: AppProspectionIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
